"""Twenty looks transcribed from grading tutorials (research_notes/styles/tutorials/).

Rows use the same format as photostyle/recipes.py:
``(tool, param, value, [sources], kind, note)``.

Kinds:
- "numeric": the tutorial states the value.
- "mid": the midpoint of a range the tutorial states.
- "converted": a stated value converted to this tool's scale. Kelvin uses
  develop.kelvin_to_temperature; a named colour uses its hue angle.
- "direction": the tutorial gives the direction only, and the amount is
  chosen here.

Each look also records the subject its tutorial was written for. That subject
picks the training photos and the example photo shown in Studio.
"""

from __future__ import annotations

from photostyle.develop import kelvin_to_temperature as K

S = {
    "RNG": ("Run N Gun Photography, Dark & Moody Lightroom Mobile Tutorial", "https://therunngun.com/dark-moody-lightroom-mobile-tutorial/"),
    "LTJ": ("lightroomtutorials.com, How to Create a Moody Jungle Green Look", "https://www.lightroomtutorials.com/jungle-green/"),
    "LS": ("Lucy Song (LR Presets), How to Edit Sunrise & Sunset Photos in Lightroom",
           "https://www.lightroompresets.com/blogs/pretty-presets-blog/how-to-edit-sunrise-and-sunset-photos-in-lightroom"),
    "HB": ("HueBliss, Golden Hour Photography Settings", "https://huebliss.com/golden-hour-photography-settings/"),
    "LPV": ("Legendary Presets, Step-by-Step Lightroom Workflow for High-Saturation Film Looks",
            "https://legendarypresets.com/step-by-step-lightroom-workflow-for-high-saturation-film-looks/"),
    "AP": ("Dylan Giannakopoulos (Australian Photography), How to edit the Milky Way in Lightroom",
           "https://www.australianphotography.com/photo-tips/how-to-edit-the-milky-way-in-lightroom"),
    "ML": ("Mikko Lagerstedt, 4 Easy Steps to Edit Astrophotography in Lightroom",
           "https://mikkolagerstedt.com/blog/how-to-edit-astrophotography-in-lightroom/"),
    "PPT": ("Presetpedia, Twilight Haze preset (night Lightroom presets)", "https://presetpedia.com/night-lightroom-presets/"),
    "LPX": ("Life Pixel, 6 Lightroom Tips for Editing Your Blue Hour Shots",
            "https://www.lifepixel.com/photo-tutorials/6-lightroom-tips-for-editing-your-blue-hour-shots"),
    "FSB": ("Fstoppers (Alex Cooke), Make Your Blue Hour Photos Stand Out", "https://fstoppers.com/lightroom/make-your-blue-hour-photos-stand-out-701417"),
    "LTT": ("lightroomtutorials.com, How to Create a Teal and Orange Look in Lightroom", "https://www.lightroomtutorials.com/teal-orange/"),
    "DTO": ("Denny's Tips, Orange and Teal Color Grading", "https://www.dennystips.com/orange-teal/"),
    "PPJ": ("Presetpedia, Moody Japan preset", "https://presetpedia.com/japan-lightroom-presets/"),
    "ESK": ("The Editing Studio, Kodachrome Film Lightroom Preset: Complete Guide",
            "https://theeditingstudio.co/blog/kodachrome-film-lightroom-preset-guide"),
    "ESK2": ("The Editing Studio, How to Get the Kodachrome Look in Lightroom",
             "https://theeditingstudio.co/blog/how-to-get-the-kodachrome-look-in-lightroom"),
    "ESV": ("The Editing Studio, Vintage Film Lightroom Preset: Complete Guide",
            "https://theeditingstudio.co/blog/vintage-clean-film-lightroom-preset-guide"),
    "LM": ("Lou & Marks Presets, CineStill 800T Film Lightroom Presets", "https://loumarkspresets.com/blogs/lightroom/cinestill-800t-free-download"),
    "TD": ("Tim Daniels (DIYPhotography), How to create the Wakui cinematic look in Lightroom and Photoshop",
           "https://www.diyphotography.net/how-to-create-the-wakui-cinematic-look-in-lightroom-and-photoshop/"),
    "LTW": ("lightroomtutorials.com, How to Achieve the Masashi Wakui Look",
            "https://www.lightroomtutorials.com/how-to-achieve-the-masashi-wakui-look/"),
    "MD": ("Diego Sanchez (Medialoot), How to Emulate the Portra 400 Film Look in Lightroom",
           "https://medialoot.com/blog/how-to-emulate-the-portra-400-film-look-in-lightroom/"),
    "PPP": ("Presetpedia, Kodak Portra 400 Classic Film preset", "https://presetpedia.com/kodak-portra-lightroom-presets/"),
    "ESA": ("The Editing Studio, Bright and Airy Lightroom Presets: Complete Guide",
            "https://theeditingstudio.co/blog/bright-and-airy-lightroom-presets"),
    "JYD": ("James Young, How to Edit Dark Witchy Portraits", "https://jamesyoungphotography.com/lightroom/cinematic-tutorial"),
    "PPB": ("Presetpedia, Vintage Emulation B&W (Tri-X 400 / HP5) preset", "https://presetpedia.com/black-and-white-lightroom-presets/"),
    "JYB": ("James Young, How To Edit Backlit Portraits: Full Breakdown", "https://jamesyoungphotography.com/lightroom/backlit-portrait"),
    "RS": ("Heather Templeton (Replica Surfaces), Light and airy food photography",
           "https://www.replicasurfaces.com/blogs/replica-surfaces-blog/how-to-take-light-and-airy-food-photos"),
    "FSA": ("Ali Tanis (FoodShot AI), Food Color Grading: How to Make Food Photos Pop", "https://foodshot.ai/blog/food-color-grading"),
    "FL": ("Flourish Presets, How to Edit Dark and Moody Photos With Moody Presets",
           "https://flourishpresets.com/blogs/flourish-presets-lightroom-presets-luts/how-to-edit-dark-and-moody-photos-moody-presets"),
    "LE": ("Legendary Presets, How to Get the Kodak Ektar 100 Look in Lightroom",
           "https://legendarypresets.com/kodak-ektar-100-lightroom-preset-guide/"),
    "WG": ("Diego Sanchez (WeGraphics), Enhance Autumn Colors in Lightroom with Ease",
           "https://we.graphics/blog/enhance-autumn-colors-in-lightroom-with-ease/"),
    "MLC": ("Mikko Lagerstedt, Cinematic Color Grading: Creating Atmosphere in Landscape Photography",
            "https://mikkolagerstedt.com/blog/cinematic-color-grading-landscape-photography/"),
    "DPSW": ("David Shaw (Digital Photography School), Tips for Processing Winter Landscapes in Lightroom",
             "https://digital-photography-school.com/tips-for-processing-winter-landscapes-in-lightroom/"),
    "PFW": ("James Abbott (Picfair Focus), How to shoot and edit snowy winter landscapes",
            "https://focus.picfair.com/articles/how-to-shoot-and-edit-snowy-landscapes"),
}


def _hsl(src, kind, hue=None, sat=None, lum=None, note=""):
    rows = []
    for key, d in (("hue", hue), ("sat", sat), ("lum", lum)):
        for band, v in (d or {}).items():
            rows.append(("hsl", f"{key}.{band}", v, [src], kind, note or f"{band} {key} {v:+g}"))
    return rows


LOOKS = {
    # ------------------------------------------------------------------ day landscapes
    "moody_forest": dict(
        title="Moody Forest", category="Day landscape",
        subject="misty, overcast forests with tall trees and lots of green", queries=["misty forest", "foggy forest overcast"],
        grade="A", rows=[
            ("exposure", "stops", -0.5, ["RNG"], "numeric", "exposure down about -0.5"),
            ("contrast", "amount", 42.5, ["RNG"], "mid", "contrast +35 to +50"),
            ("tone_regions", "highlights", -100, ["RNG"], "numeric", "highlights -100"),
            ("tone_regions", "shadows", 100, ["RNG"], "numeric", "shadows +100"),
            ("tone_regions", "whites", 25, ["RNG"], "numeric", "whites +25ish"),
            ("tone_regions", "blacks", -25, ["RNG"], "numeric", "blacks -25"),
            ("point_curve", "rgb", [(0, 22), (64, 50), (192, 205), (255, 255)], ["RNG"], "direction",
             "fairly strong S-curve, shadow point lifted about 0.75 stops"),
            ("white_balance", "temperature", -10, ["RNG"], "numeric", "temperature -10"),
            ("white_balance", "tint", -5, ["RNG"], "numeric", "tint toward green -5"),
            ("saturation", "sat", -50, ["RNG"], "numeric", "saturation about -50"),
            *_hsl("RNG", "numeric", hue={"red": 20, "green": 50, "aqua": 40, "blue": -20},
                  sat={"red": -30, "orange": -10, "yellow": -30, "green": -80, "aqua": -30, "blue": -30},
                  lum={"orange": 80, "green": 40, "aqua": 30, "blue": 10}),
            ("color_grading", "highlights", (100, 10), ["RNG"], "direction", "green in the highlights, saturation at most +10"),
            ("color_grading", "shadows", (250, 10), ["RNG"], "direction", "purple/blue in the shadows, saturation at most +10"),
            ("dehaze", "amount", 10, ["RNG"], "direction", "dehaze slightly up"),
            ("vignette", "amount", -25, ["LTJ"], "numeric", "vignette -25"),
        ]),
    "golden_hour": dict(
        title="Golden Hour", category="Day landscape",
        subject="sunrise and sunset landscapes", queries=["sunset landscape mountains", "sunrise landscape"],
        grade="B", rows=[
            ("tone_regions", "highlights", -100, ["LS"], "numeric", "highlights -100"),
            ("tone_regions", "shadows", 32, ["LS"], "numeric", "shadows +32"),
            ("tone_regions", "blacks", 60, ["LS"], "numeric", "blacks +60"),
            ("color_grading", "highlights", (40, 15), ["HB"], "numeric", "highlights hue 40, saturation 15"),
            ("color_grading", "shadows", (220, 10), ["HB"], "numeric", "shadows hue 220, saturation 10"),
            ("saturation", "vibrance", 15, ["LS"], "direction", "vibrance up"),
            ("dehaze", "amount", 10, ["LS"], "direction", "dehaze up"),
        ]),
    "velvia": dict(
        title="Velvia Vivid", category="Day landscape",
        subject="sunny landscapes with sky, water and foliage", queries=["mountain lake landscape sunny", "green valley landscape"],
        grade="A", rows=[
            ("saturation", "vibrance", 15, ["LPV"], "mid", "vibrance +10 to +20"),
            ("saturation", "sat", -1.5, ["LPV"], "mid", "saturation 0 to -3"),
            ("tone_regions", "highlights", -22.5, ["LPV"], "mid", "highlights -15 to -30"),
            ("tone_regions", "whites", -10, ["LPV"], "mid", "whites -5 to -15"),
            ("point_curve", "rgb", [(0, 10), (255, 255)], ["LPV"], "numeric", "black point lifted +10"),
            *_hsl("LPV", "mid", hue={"yellow": -8, "green": -8, "aqua": 5},
                  sat={"yellow": 24, "green": 22.5, "aqua": 15, "blue": 17.5, "red": 10},
                  lum={"green": -5, "aqua": -10, "blue": -15, "red": -5}, note="Velvia 100 colour table"),
            ("color_grading", "shadows", (300, 10), ["LPV"], "converted", "shadows magenta +8 to +12 (magenta = hue 300)"),
        ]),
    # ------------------------------------------------------------------ night landscapes
    "milky_way": dict(
        title="Milky Way", category="Night landscape",
        subject="night skies and the Milky Way over a landscape", queries=["milky way night sky", "astrophotography stars landscape"],
        grade="A", rows=[
            ("white_balance", "temperature", K(4510), ["AP"], "converted", "temperature 4510 K"),
            ("white_balance", "tint", 10, ["AP"], "numeric", "tint +10"),
            ("exposure", "stops", 0.4, ["AP"], "numeric", "exposure +0.40"),
            ("contrast", "amount", 50, ["AP"], "numeric", "contrast +50"),
            ("tone_regions", "shadows", 5, ["AP"], "numeric", "shadows +5"),
            ("tone_regions", "whites", 25, ["AP"], "numeric", "whites +25"),
            ("tone_regions", "blacks", -25, ["AP"], "numeric", "blacks -25"),
            ("parametric_curve", "highlights", 10, ["AP"], "numeric", "curve highlights +10"),
            ("parametric_curve", "lights", 5, ["AP"], "numeric", "curve lights +5"),
            ("parametric_curve", "darks", -15, ["AP"], "numeric", "curve darks -15"),
            ("parametric_curve", "shadows", 15, ["AP"], "numeric", "curve shadows +15"),
            ("dehaze", "amount", 25, ["AP"], "numeric", "dehaze +25"),
            ("saturation", "vibrance", 20, ["AP"], "numeric", "vibrance +20"),
            ("saturation", "sat", 10, ["AP"], "numeric", "saturation +10"),
            ("vignette", "amount", -9, ["ML"], "numeric", "vignette -9"),
        ]),
    "blue_hour": dict(
        title="Blue Hour", category="Night landscape",
        subject="twilight seascapes and landscapes after sunset", queries=["blue hour seascape", "twilight coast dusk"],
        grade="C", rows=[
            ("contrast", "amount", -25, ["PPT"], "numeric", "contrast -25 (preset listing, weak source)"),
            ("tone_regions", "shadows", 45, ["PPT"], "numeric", "shadows +45"),
            ("white_balance", "temperature", -15, ["PPT", "LPX"], "numeric", "temperature -15; err on the cool side"),
            ("saturation", "vibrance", 20, ["PPT"], "numeric", "vibrance +20"),
            ("color_grading", "midtones", (270, 10), ["PPT"], "converted", "purple tint +10 (purple = hue 270)"),
            ("dehaze", "amount", -20, ["PPT"], "numeric", "dehaze -20"),
            ("hsl", "hue.yellow", -20, ["FSB"], "direction", "yellows toward orange"),
            ("hsl", "hue.blue", -20, ["FSB"], "direction", "blues toward cyan"),
            ("point_curve", "rgb", [(0, 0), (64, 56), (192, 200), (255, 255)], ["LPX"], "direction", "gentle S-curve"),
        ]),
    # ------------------------------------------------------------------ day cities
    "teal_orange": dict(
        title="Teal & Orange", category="Day city",
        subject="city streets and architecture in daylight", queries=["city street daytime", "downtown architecture street"],
        grade="B", rows=[
            *_hsl("LTT", "numeric", hue={"red": 100, "yellow": -100, "green": 100, "blue": -100},
                  note="colour mixer hue: red +100, yellow -100, green +100, blue -100"),
            ("calibration", "blue_hue", -100, ["DTO"], "numeric", "blue primary hue -100"),
            ("calibration", "red_hue", 50, ["DTO"], "numeric", "red primary hue about +50"),
            ("color_grading", "shadows", (195, 25), ["PPJ"], "numeric", "shadows hue 195, saturation 25"),
            ("color_grading", "highlights", (35, 20), ["PPJ"], "numeric", "highlights hue 35, saturation 20"),
            ("point_curve", "rgb", [(0, 18), (64, 55), (192, 205), (255, 245)], ["LTT"], "direction",
             "drag the end points in for a fade, then an S-curve"),
        ]),
    "kodachrome": dict(
        title="Kodachrome Street", category="Day city",
        subject="colourful street and travel scenes in daylight", queries=["colorful street market", "street photography colorful"],
        grade="A", rows=[
            ("exposure", "stops", 0.15, ["ESK"], "mid", "exposure 0 to +0.3"),
            ("contrast", "amount", 15, ["ESK"], "mid", "contrast +10 to +20"),
            ("tone_regions", "highlights", -20, ["ESK"], "mid", "highlights -15 to -25"),
            ("tone_regions", "shadows", 10, ["ESK"], "mid", "shadows +5 to +15"),
            ("tone_regions", "whites", -10, ["ESK"], "mid", "whites -5 to -15"),
            ("tone_regions", "blacks", 5, ["ESK"], "mid", "blacks 0 to +10 (ESK2 says 0 to -10; ESK followed)"),
            ("saturation", "vibrance", 15, ["ESK"], "mid", "vibrance +10 to +20"),
            ("saturation", "sat", 2.5, ["ESK"], "mid", "saturation 0 to +5"),
            *_hsl("ESK", "mid", hue={"red": 5, "orange": -5, "blue": 7.5},
                  sat={"red": 20, "orange": 12.5, "yellow": 7.5, "blue": 25}, lum={"orange": 12.5, "blue": -12.5}),
            ("point_curve", "rgb", [(0, 4), (64, 54), (192, 206), (255, 240)], ["ESK2"], "mid",
             "shadow point output 0-8, highlight point 235-245, pronounced S (S shape chosen)"),
            ("color_grading", "highlights", (40, 5), ["ESK"], "direction", "neutral to very slight warm"),
        ]),
    "matte_urban": dict(
        title="Matte Urban", category="Day city",
        subject="streets, walls and urban textures", queries=["urban alley street", "city street wall"],
        grade="A", rows=[
            ("exposure", "stops", 0.3, ["ESV"], "mid", "exposure +0.2 to +0.4"),
            ("contrast", "amount", -25, ["ESV"], "mid", "contrast -20 to -30"),
            ("tone_regions", "highlights", -27.5, ["ESV"], "mid", "highlights -20 to -35"),
            ("tone_regions", "shadows", 27.5, ["ESV"], "mid", "shadows +20 to +35"),
            ("tone_regions", "whites", -20, ["ESV"], "mid", "whites -15 to -25"),
            ("tone_regions", "blacks", 27.5, ["ESV"], "mid", "blacks +20 to +35"),
            ("point_curve", "rgb", [(0, 25), (255, 242)], ["ESV"], "mid", "black point up 20-30 units; soften the top (chosen)"),
            ("color_grading", "shadows", (35, 25), ["ESV"], "converted", "warm amber shadows, saturation 20-30 (amber = hue 35)"),
            ("color_grading", "highlights", (50, 8), ["ESV"], "direction", "slight warm yellow highlights"),
            *_hsl("ESV", "mid", hue={"yellow": 7.5, "green": 12.5, "blue": 5},
                  sat={"green": -25, "blue": -30, "aqua": -17.5, "red": -2.5}, lum={"orange": 12.5, "yellow": 7.5}),
            ("vignette", "amount", -15, ["ESV"], "mid", "vignette -10 to -20"),
        ]),
    # ------------------------------------------------------------------ night cities
    "cinestill_800t": dict(
        title="CineStill 800T", category="Night city",
        subject="city streets at night under street and shop lights", queries=["city street night lights", "night street rain"],
        grade="B", rows=[
            ("exposure", "stops", 0.35, ["LM"], "mid", "exposure +0.20 to +0.50"),
            ("contrast", "amount", 15, ["LM"], "numeric", "contrast +15"),
            ("tone_regions", "highlights", -25, ["LM"], "numeric", "highlights -25"),
            ("tone_regions", "shadows", 15, ["LM"], "mid", "shadows +10 to +20"),
            ("tone_regions", "whites", 10, ["LM"], "numeric", "whites +10"),
            ("tone_regions", "blacks", -20, ["LM"], "numeric", "blacks -20"),
            ("white_balance", "temperature", -10, ["LM"], "direction", "slightly cooler than the starting white balance"),
            ("white_balance", "tint", 5.5, ["LM"], "mid", "tint +3 to +8 toward magenta"),
            ("saturation", "vibrance", -5, ["LM"], "numeric", "vibrance -5"),
            ("saturation", "sat", -5, ["LM"], "numeric", "saturation -5"),
            ("dehaze", "amount", 5, ["LM"], "numeric", "dehaze +5"),
            ("color_grading", "shadows", (185, 15), ["LM"], "direction", "teal/cyan shadows, low saturation"),
            ("color_grading", "highlights", (20, 15), ["LM"], "direction", "orange-red highlights, low saturation"),
            ("hsl", "sat.yellow", -15, ["LM"], "direction", "lower yellow saturation"),
            ("hsl", "sat.green", -15, ["LM"], "direction", "lower green saturation"),
            ("hsl", "hue.blue", -10, ["LM"], "direction", "blues cooler"),
            ("hsl", "hue.aqua", 10, ["LM"], "direction", "aquas cooler"),
            ("vignette", "amount", -7.5, ["LM"], "mid", "vignette -5 to -10"),
        ]),
    "tokyo_night": dict(
        title="Tokyo Night", category="Night city",
        subject="neon-lit night streets (Masashi Wakui style)", queries=["tokyo night street", "neon night alley japan"],
        grade="B", rows=[
            ("white_balance", "temperature", 100, ["TD"], "converted", "temperature all the way right (50000), tint 0"),
            ("color_grading", "highlights", (60, 50), ["TD"], "numeric", "split toning highlights hue ~60, saturation 50"),
            ("color_grading", "shadows", (225, 100), ["TD"], "numeric", "split toning shadows hue ~225, saturation 100"),
            ("calibration", "shadow_tint", -100, ["TD"], "numeric", "calibration shadows tint -100"),
            ("point_curve", "rgb", [(0, 20), (255, 255)], ["TD", "LTW"], "direction", "RGB curve toe up"),
            ("point_curve", "g", [(0, 10), (255, 240)], ["TD", "LTW"], "direction", "green toe up; green top point down"),
            ("point_curve", "b", [(0, 0), (255, 225)], ["TD", "LTW"], "direction", "blue top point down, twice the green amount"),
            ("contrast", "amount", -15, ["TD"], "direction", "contrast down"),
            ("tone_regions", "highlights", 15, ["TD"], "direction", "highlights up"),
            ("tone_regions", "whites", -15, ["TD"], "direction", "whites down"),
            ("saturation", "vibrance", 10, ["TD"], "direction", "a little vibrance"),
        ]),
    # ------------------------------------------------------------------ portraits
    "portra_400": dict(
        title="Portra 400", category="Portrait",
        subject="daylight portraits outdoors", queries=["outdoor portrait natural light", "portrait woman park"],
        grade="A", rows=[
            ("point_curve", "rgb", [(0, 0), (30, 25), (70, 75), (115, 120), (190, 170), (255, 255)], ["MD"], "numeric", "RGB point curve"),
            ("point_curve", "r", [(0, 0), (40, 20), (85, 65), (145, 170), (205, 225), (255, 255)], ["MD"], "numeric", "red point curve"),
            ("point_curve", "g", [(0, 0), (40, 20), (80, 60), (135, 155), (185, 210), (255, 255)], ["MD"], "numeric", "green point curve"),
            ("point_curve", "b", [(0, 0), (40, 25), (120, 120), (175, 205), (215, 235), (255, 255)], ["MD"], "numeric", "blue point curve"),
            ("exposure", "stops", 0.45, ["PPP"], "numeric", "exposure +0.45"),
            ("contrast", "amount", -15, ["PPP"], "numeric", "contrast -15"),
            ("tone_regions", "highlights", -30, ["PPP"], "numeric", "highlights -30"),
            ("tone_regions", "shadows", 35, ["PPP"], "numeric", "shadows +35"),
            ("tone_regions", "whites", 15, ["PPP"], "numeric", "whites +15"),
            ("tone_regions", "blacks", 20, ["PPP"], "numeric", "blacks +20"),
            ("white_balance", "temperature", 200 / 30, ["PPP"], "converted", "temperature +200 K"),
            ("white_balance", "tint", 8, ["PPP"], "numeric", "tint +8"),
            ("saturation", "vibrance", 12, ["PPP"], "numeric", "vibrance +12"),
            ("saturation", "sat", -8, ["PPP"], "numeric", "saturation -8"),
            *_hsl("PPP", "numeric", hue={"red": 5, "yellow": 8, "blue": 10}, sat={"orange": -10}, lum={"orange": 15}),
            ("color_grading", "shadows", (200, 12), ["PPP"], "numeric", "shadows hue 200, saturation 12"),
            ("color_grading", "highlights", (35, 8), ["PPP"], "numeric", "highlights hue 35, saturation 8"),
            ("vignette", "amount", -12, ["PPP"], "numeric", "vignette -12"),
        ]),
    "bright_airy": dict(
        title="Bright & Airy", category="Portrait",
        subject="weddings and lifestyle portraits in soft light", queries=["wedding bride portrait", "window light portrait"],
        grade="A", rows=[
            ("exposure", "stops", 0.45, ["ESA"], "mid", "exposure +0.3 to +0.6"),
            ("contrast", "amount", -25, ["ESA"], "mid", "contrast -20 to -30"),
            ("tone_regions", "highlights", -32.5, ["ESA"], "mid", "highlights -25 to -40"),
            ("tone_regions", "shadows", 22.5, ["ESA"], "mid", "shadows +15 to +30"),
            ("tone_regions", "whites", -15, ["ESA"], "mid", "whites -10 to -20"),
            ("tone_regions", "blacks", 20, ["ESA"], "mid", "blacks +15 to +25"),
            ("saturation", "vibrance", -2.5, ["ESA"], "mid", "vibrance -5 to 0"),
            ("saturation", "sat", -2.5, ["ESA"], "mid", "saturation -5 to 0"),
            *_hsl("ESA", "mid", sat={"green": -12.5, "blue": -17.5, "aqua": -10}, lum={"orange": 12.5, "yellow": 7.5}),
            ("point_curve", "rgb", [(0, 15), (255, 245)], ["ESA"], "direction", "lift the black point, pull the top anchor down slightly"),
            ("color_grading", "shadows", (210, 5), ["ESA"], "direction", "neutral or very slight cool tint in shadows"),
        ]),
    "moody_portrait": dict(
        title="Moody Portrait", category="Portrait",
        subject="low-key and indoor portraits", queries=["low key portrait", "dark moody portrait"],
        grade="A", rows=[
            ("contrast", "amount", 6, ["JYD"], "numeric", "contrast +6"),
            ("tone_regions", "highlights", 7, ["JYD"], "numeric", "highlights +7"),
            ("tone_regions", "shadows", 60, ["JYD"], "numeric", "shadows +60"),
            ("tone_regions", "whites", -30, ["JYD"], "numeric", "whites -30"),
            ("tone_regions", "blacks", -15, ["JYD"], "numeric", "blacks -15"),
            ("white_balance", "temperature", K(7555), ["JYD"], "converted", "temperature 7555 K"),
            ("white_balance", "tint", 18, ["JYD"], "numeric", "tint +18"),
            ("saturation", "vibrance", -8, ["JYD"], "numeric", "vibrance -8"),
            ("saturation", "sat", -2, ["JYD"], "numeric", "saturation -2"),
            *_hsl("JYD", "numeric", hue={"red": -9, "orange": 6, "yellow": 3, "green": -92},
                  sat={"red": 7, "orange": 2, "yellow": -27, "green": -38},
                  lum={"red": -20, "orange": -6, "yellow": -6, "green": -65}),
            ("point_curve", "rgb", [(0, 8), (64, 58), (192, 200), (255, 250)], ["JYD"], "direction", "gentle S-curve"),
        ]),
    "tri_x": dict(
        title="Tri-X B&W", category="Portrait",
        subject="street and documentary portraits in black and white", queries=["street portrait man", "documentary portrait"],
        grade="C", rows=[
            ("contrast", "amount", 25, ["PPB"], "numeric", "contrast +25 (preset listing, weak source)"),
            ("tone_regions", "highlights", -25, ["PPB"], "numeric", "highlights -25"),
            ("tone_regions", "shadows", 30, ["PPB"], "numeric", "shadows +30"),
            ("tone_regions", "whites", 15, ["PPB"], "numeric", "whites +15"),
            ("tone_regions", "blacks", -15, ["PPB"], "numeric", "blacks -15"),
            ("black_white", "mix.red", 25, ["PPB"], "numeric", "B&W mix reds +25"),
            ("dehaze", "amount", 5, ["PPB"], "numeric", "dehaze +5"),
            ("parametric_curve", "highlights", -10, ["PPB"], "numeric", "curve highlights -10"),
            ("parametric_curve", "shadows", 10, ["PPB"], "numeric", "curve shadows +10"),
        ]),
    "golden_backlit": dict(
        title="Golden Backlit", category="Portrait",
        subject="backlit portraits at sunset", queries=["backlit portrait sunset", "golden hour portrait"],
        grade="A", rows=[
            ("contrast", "amount", -10, ["JYB"], "numeric", "contrast -10"),
            ("tone_regions", "highlights", 22, ["JYB"], "numeric", "highlights +22"),
            ("tone_regions", "shadows", 15, ["JYB"], "numeric", "shadows +15"),
            ("tone_regions", "blacks", -66, ["JYB"], "numeric", "blacks -66"),
            ("dehaze", "amount", -13, ["JYB"], "numeric", "dehaze -13"),
            ("saturation", "vibrance", 19, ["JYB"], "numeric", "vibrance +19"),
            ("saturation", "sat", 4, ["JYB"], "numeric", "saturation +4"),
            ("white_balance", "temperature", K(4669), ["JYB"], "converted", "temperature 4669 K"),
            ("white_balance", "tint", 8, ["JYB"], "numeric", "tint +8"),
            ("point_curve", "rgb", [(0, 13), (77, 57), (148, 140), (255, 239)], ["JYB"], "numeric", "tone curve points"),
            ("color_grading", "midtones", (197, 9), ["JYB"], "numeric", "midtones hue 197, saturation 9"),
            *_hsl("JYB", "numeric",
                  hue={"red": -14, "orange": 2, "yellow": 1, "green": 10, "aqua": 14, "blue": 12, "purple": 2, "magenta": 5},
                  sat={"red": 6, "orange": 1, "yellow": -25, "green": -11, "aqua": -23, "blue": -29, "purple": -10, "magenta": -10},
                  lum={"red": -10, "yellow": 10, "blue": 3}),
        ]),
    # ------------------------------------------------------------------ objects and food
    "bright_food": dict(
        title="Bright Food", category="Food & objects",
        subject="food on light tables, overhead and daylight", queries=["food flat lay", "breakfast table food"],
        grade="B", rows=[
            ("exposure", "stops", 0.25, ["RS"], "numeric", "exposure +0.25"),
            ("tone_regions", "highlights", -100, ["RS"], "numeric", "highlights all the way down"),
            ("tone_regions", "whites", 35, ["RS"], "numeric", "whites around 35"),
            ("tone_regions", "shadows", 75, ["RS"], "numeric", "shadows around 75"),
            ("white_balance", "temperature", K(5750), ["FSA"], "converted", "about 5500-6000 K"),
            ("white_balance", "tint", 7.5, ["FSA"], "mid", "tint toward magenta +5 to +10"),
            ("point_curve", "rgb", [(0, 19), (64, 60), (192, 200), (255, 255)], ["FSA"], "mid",
             "black point lifted 5-10 %, gentle S-curve (S chosen)"),
            *_hsl("FSA", "mid", hue={"red": 7.5}, sat={"yellow": 12.5, "red": 7.5}, lum={"yellow": -17.5, "green": 7.5}),
            ("color_grading", "shadows", (200, 6.5), ["FSA"], "converted", "cool blue/teal shadows, saturation 5-8 %"),
            ("color_grading", "balance", 15, ["FSA"], "mid", "balance +10 to +20"),
        ]),
    "moody_food": dict(
        title="Moody Food", category="Food & objects",
        subject="food, drinks and still life on dark surfaces", queries=["dark food photography", "coffee cup dark background"],
        grade="A", rows=[
            ("exposure", "stops", -0.5, ["FL"], "mid", "exposure -0.3 to -0.7"),
            ("contrast", "amount", 40, ["FL"], "mid", "contrast +30 to +50"),
            ("tone_regions", "highlights", -70, ["FL"], "mid", "highlights -60 to -80"),
            ("tone_regions", "shadows", 40, ["FL"], "mid", "shadows +30 to +50"),
            ("tone_regions", "whites", -30, ["FL"], "mid", "whites -20 to -40"),
            ("tone_regions", "blacks", -25, ["FL"], "mid", "blacks -20 to -30"),
            ("saturation", "vibrance", -15, ["FL"], "mid", "vibrance -10 to -20"),
            ("saturation", "sat", -20, ["FL"], "mid", "saturation -15 to -25"),
            *_hsl("FL", "numeric", sat={"blue": -20, "green": -30, "yellow": -15}),
            ("hsl", "lum.orange", -10, ["FL"], "direction", "warm luminance reduced"),
            ("color_grading", "highlights", (200, 10), ["FL"], "direction", "cool highlights"),
            ("color_grading", "shadows", (30, 10), ["FL"], "direction", "warm shadows"),
            ("color_grading", "balance", -15, ["FL"], "numeric", "balance -15"),
            ("calibration", "shadow_tint", 10, ["FL"], "numeric", "shadow tint +10"),
            ("calibration", "blue_hue", -10, ["FL"], "numeric", "blue primary hue -10"),
            ("calibration", "blue_sat", -20, ["FL"], "numeric", "blue primary saturation -20"),
            ("vignette", "amount", -20, ["FL"], "numeric", "vignette -20"),
            ("point_curve", "rgb", [(0, 0), (64, 50), (192, 207), (255, 255)], ["FL"], "direction", "S-curve"),
        ]),
    "ektar_100": dict(
        title="Ektar 100", category="Food & objects",
        subject="colourful travel scenes and objects in daylight", queries=["colorful building travel", "colorful umbrellas street"],
        grade="A", rows=[
            ("white_balance", "temperature", K(5350), ["LE"], "converted", "5200-5500 K"),
            ("white_balance", "tint", -6.5, ["LE"], "mid", "tint -5 to -8"),
            ("tone_regions", "highlights", -25, ["LE"], "mid", "highlights -20 to -30"),
            ("tone_regions", "whites", -10, ["LPV"], "mid", "whites -5 to -15"),
            ("saturation", "vibrance", 15, ["LPV"], "mid", "vibrance +10 to +20"),
            ("point_curve", "rgb", [(0, 10), (64, 58), (192, 200), (255, 255)], ["LE"], "numeric",
             "shadow lift +10 at the bottom-left point, gentle S (S chosen)"),
            *_hsl("LPV", "mid", hue={"yellow": -5, "green": -5},
                  sat={"red": 21.5, "orange": -6.5, "yellow": 5, "green": 5, "aqua": 8, "blue": 11},
                  lum={"red": -9, "orange": -5, "yellow": -5, "aqua": -8, "blue": -13.5}, note="Ektar colour table"),
        ]),
    # ------------------------------------------------------------------ seasons
    "autumn": dict(
        title="Autumn", category="Seasons",
        subject="autumn foliage and cosy autumn scenes", queries=["autumn leaves forest", "fall foliage trees"],
        grade="A", rows=[
            ("white_balance", "temperature", 5, ["WG"], "numeric", "temperature +5"),
            ("exposure", "stops", 0.3, ["WG"], "numeric", "exposure +0.30"),
            ("contrast", "amount", -20, ["WG"], "numeric", "contrast -20"),
            ("tone_regions", "highlights", 20, ["WG"], "numeric", "highlights +20"),
            ("tone_regions", "shadows", 40, ["WG"], "numeric", "shadows +40"),
            ("tone_regions", "whites", -20, ["WG"], "numeric", "whites -20"),
            ("tone_regions", "blacks", -20, ["WG"], "numeric", "blacks -20"),
            ("saturation", "vibrance", 30, ["WG"], "numeric", "vibrance +30"),
            ("saturation", "sat", -20, ["WG"], "numeric", "saturation -20"),
            ("point_curve", "rgb", [(0, 0), (65, 45), (130, 120), (195, 190), (255, 255)], ["WG"], "numeric", "point curve"),
            *_hsl("WG", "numeric", hue={"orange": -10, "yellow": -65, "green": -100},
                  sat={"red": -20, "orange": 30, "yellow": -20, "green": -40, "aqua": -20, "blue": -20},
                  lum={"red": 10, "orange": -10, "yellow": -20, "green": -20, "aqua": -20, "blue": -20}),
            ("color_grading", "shadows", (30, 20), ["WG"], "numeric", "shadows hue 30, saturation 20"),
        ]),
    "winter": dict(
        title="Winter", category="Seasons",
        subject="snowy landscapes", queries=["snowy landscape", "snow mountains winter"],
        grade="C", rows=[
            ("color_grading", "shadows", (215, 12.5), ["MLC"], "mid", "shadows hue 210-220, saturation 10-15"),
            ("color_grading", "highlights", (40, 7.5), ["MLC"], "mid", "highlights hue 35-45, saturation 5-10"),
            ("hsl", "hue.blue", -12.5, ["MLC"], "mid", "blue hue toward aqua, -10 to -15 (for snow)"),
            ("contrast", "amount", 16, ["DPSW"], "numeric", "contrast +16 (example image)"),
            ("vignette", "amount", -20, ["DPSW"], "numeric", "post-crop vignette -20"),
            ("exposure", "stops", -0.1, ["PFW"], "numeric", "exposure -0.10"),
            ("tone_regions", "whites", -15, ["PFW"], "mid", "whites -10 to -20"),
            ("white_balance", "temperature", 100 / 30, ["PFW"], "converted", "temperature raised 9400 -> 9500 K"),
        ]),
}

NOT_MODELLED = ("local adjustments (graduated/radial filters, brushes), clarity, texture, sharpening, noise reduction, "
                "grain and halation are not modelled by a global, editable renderer")
